import openai

# Set your OpenAI API key
openai.api_key = ""

# Create a chat response by providing prompts in the form of messages, and specifying the GPT model to use
ai_response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
            # Start the conversation with a system prompt
            {"role": "system", "content": "You are a chatbot"},
            # Ask the user to provide inputs for the cover letter
            {"role": "user", "content": "Make a persuasive cover letter, name: , position applying to: , "
                                        "years of experience: , Location based: , Teacher reference: , "
                                        "educational background: , hobbies:" + input("Enter name: ") +
                                        input("Enter position applying to: ") +
                                        input("Enter number years of experience: ") + input("Location based: ")
                                        + input("Enter reference: ") + input("Enter your educational background: ")
                                        + input("Enter hobbies: ")
             }
        ]
)

# Extract the response from ChatGPT
info = ''
for choice in ai_response.choices:
    info += choice.message.content

# Print the response generated by GPT
print(info)
